# Generated by Django 5.1.7 on 2025-03-30 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Наименование категории")),
                (
                    "description",
                    models.TextField(blank=True, max_length=250, null=True, verbose_name="Описание категории"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Наименование продукта")),
                ("description", models.TextField(max_length=250, verbose_name="Описание продукта")),
                ("catalog_image", models.ImageField(blank=True, null=True, upload_to="images/")),
                ("cost", models.IntegerField(verbose_name="Цена за покупку")),
                ("created_at", models.DateField(verbose_name="Дата создания")),
                ("updated_at", models.DateField(verbose_name="Дата последнего изменения")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["name", "category"],
            },
        ),
    ]
